// Code generated by BqLog_CategoryLogGenerator; DO NOT EDIT.
// Copyright (C) 2026 Tencent. Licensed under the Apache License, Version 2.0.
// Change the package declaration to the package of your application.
package bqlog_categories

import (
	bq "github.com/Tencent/BqLog/go/v2"
)

type Generated_category_Category uint32

const (
	Generated_category_Category_Default                       Generated_category_Category = 0
	Generated_category_Category__7_ModuleA                    Generated_category_Category = 1
	Generated_category_Category__7_ModuleA_7_SystemA          Generated_category_Category = 2
	Generated_category_Category__7_ModuleA_7_SystemA_6_ClassA Generated_category_Category = 3
	Generated_category_Category__7_ModuleB                    Generated_category_Category = 4
	Generated_category_Category__3_A_B                        Generated_category_Category = 5
	Generated_category_Category__1_A                          Generated_category_Category = 6
	Generated_category_Category__1_A_1_B                      Generated_category_Category = 7
)

var Generated_category_category_names = []string{
	"",
	"ModuleA",
	"ModuleA.SystemA",
	"ModuleA.SystemA.ClassA",
	"ModuleB",
	"A_B",
	"A",
	"A.B",
}

type Generated_category struct {
	*bq.Category_log
}

func Create_Generated_category(name, config string) *Generated_category {
	return &Generated_category{bq.Create_category_log(name, config, Generated_category_category_names)}
}

func Get_Generated_category_by_name(name string) *Generated_category {
	base := bq.Get_log_by_name(name)
	if base.Is_valid() && base.Get_categories_count() == len(Generated_category_category_names) {
		for index, category := range Generated_category_category_names {
			if base.Get_category_name(index) != category {
				return &Generated_category{&bq.Category_log{Log: &bq.Log{}}}
			}
		}
		return &Generated_category{&bq.Category_log{Log: base}}
	}
	return &Generated_category{&bq.Category_log{Log: &bq.Log{}}}
}

func (l *Generated_category) Verbose_c(category Generated_category_Category, format string, args ...bq.Arg) bool {
	return l.Category_log.Verbose_c(uint32(category), format, args...)
}
func (l *Generated_category) Debug_c(category Generated_category_Category, format string, args ...bq.Arg) bool {
	return l.Category_log.Debug_c(uint32(category), format, args...)
}
func (l *Generated_category) Info_c(category Generated_category_Category, format string, args ...bq.Arg) bool {
	return l.Category_log.Info_c(uint32(category), format, args...)
}
func (l *Generated_category) Warning_c(category Generated_category_Category, format string, args ...bq.Arg) bool {
	return l.Category_log.Warning_c(uint32(category), format, args...)
}
func (l *Generated_category) Error_c(category Generated_category_Category, format string, args ...bq.Arg) bool {
	return l.Category_log.Error_c(uint32(category), format, args...)
}
func (l *Generated_category) Fatal_c(category Generated_category_Category, format string, args ...bq.Arg) bool {
	return l.Category_log.Fatal_c(uint32(category), format, args...)
}
