/* Copyright (C) 2026 Tencent. Licensed under the Apache License, Version 2.0. */
#include "template/category_log_template_go.h"

namespace bq {
    bq::string category_log_template_go::field_name(const bq::string& segment)
    {
        // Exported Go fields start with an upper case letter.
        if (segment.is_empty() || segment[0] < 'a' || segment[0] > 'z') {
            return segment;
        }
        bq::string result;
        result.push_back(static_cast<bq::string::value_type>(segment[0] - 'a' + 'A'));
        result += segment.substr(1);
        return result;
    }

    bq::string category_log_template_go::node_type_name(const category_node& node) const
    {
        // Length-prefixed segments avoid collisions between A.B and A_B.
        bq::string suffix;
        for (const auto& segment : node.full_name().split(".")) {
            suffix += "_" + uint64_to_string(static_cast<uint64_t>(segment.size())) + "_" + segment;
        }
        return class_name_ + "_node" + suffix;
    }

    bq::string category_log_template_go::field_path(const category_node& node) const
    {
        bq::string path;
        for (const auto& segment : node.full_name().split(".")) {
            if (!path.is_empty()) {
                path += ".";
            }
            path += field_name(segment);
        }
        return path;
    }

    bq::string category_log_template_go::category_names(const category_node& node) const
    {
        bq::string code = "\t\"" + node.full_name() + "\",\n";
        for (const auto& child : node.get_all_children()) {
            code += category_names(*child);
        }
        return code;
    }

    bq::string category_log_template_go::category_types(const category_node& node, const bq::string& type_name) const
    {
        bq::string code = "type " + type_name + " struct {\n";
        if (node.parent()) {
            code += "\t" + class_name_ + "_Category\n";
        }
        for (const auto& child : node.get_all_children()) {
            bq::string child_type = class_name_ + "_Category";
            if (child->get_all_children().size() > 0) {
                child_type = node_type_name(*child);
            }
            code += "\t" + field_name(child->name()) + " " + child_type + " // " + child->full_name();
            if (!child->comment().trim().is_empty()) {
                code += " - " + child->comment().trim();
            }
            code += "\n";
        }
        code += "}\n\n";
        for (const auto& child : node.get_all_children()) {
            if (child->get_all_children().size() > 0) {
                code += category_types(*child, node_type_name(*child));
            }
        }
        return code;
    }

    bq::string category_log_template_go::category_init(const category_node& node, uint64_t& index) const
    {
        bq::string code;
        for (const auto& child : node.get_all_children()) {
            ++index;
            bq::string path = "root." + field_path(*child);
            if (child->get_all_children().size() > 0) {
                code += "\t" + path + "." + class_name_ + "_Category = " + uint64_to_string(index) + "\n";
                code += category_init(*child, index);
            } else {
                code += "\t" + path + " = " + uint64_to_string(index) + "\n";
            }
        }
        return code;
    }

    bq::string category_log_template_go::format(const bq::string& template_string, const category_node& root_node) const
    {
        uint64_t index = 0;
        bq::string code = template_string.replace("${CLASS_NAME}", class_name_);
        code = code.replace("${CATEGORY_TYPES}", category_types(root_node, class_name_ + "_category_root"));
        code = code.replace("${CATEGORY_INIT}", category_init(root_node, index));
        return code.replace("${CATEGORY_NAMES}", category_names(root_node));
    }

    bq::string category_log_template_go::get_template_content() const
    {
        return R"(// Code generated by BqLog_CategoryLogGenerator; DO NOT EDIT.
// Copyright (C) 2026 Tencent. Licensed under the Apache License, Version 2.0.
// Change the package declaration to the package of your application.
//
// Usage:
//     log := Create_${CLASS_NAME}(log_name, log_config)
//     log.Info("content")                            // empty category
//     log.Info_c(log.Cat.ModuleA.SystemA, "content") // a log entry for category ModuleA.SystemA, generated from your Category Config File
package bqlog_categories

import (
    bq "github.com/Tencent/BqLog/wrapper/go/src/bq"
)

type ${CLASS_NAME}_Category uint32

func (c ${CLASS_NAME}_Category) category_index() uint32 { return uint32(c) }

type ${CLASS_NAME}_Category_ref interface {
    category_index() uint32
}

${CATEGORY_TYPES}
func new_${CLASS_NAME}_category_root() ${CLASS_NAME}_category_root {
    var root ${CLASS_NAME}_category_root
${CATEGORY_INIT}    return root
}

var ${CLASS_NAME}_category_names = []string{
${CATEGORY_NAMES}}

type ${CLASS_NAME} struct {
    *bq.Category_log
    Cat ${CLASS_NAME}_category_root
}

func Create_${CLASS_NAME}(name, config string) *${CLASS_NAME} {
    return &${CLASS_NAME}{Category_log: bq.Create_category_log(name, config, ${CLASS_NAME}_category_names), Cat: new_${CLASS_NAME}_category_root()}
}

func Get_${CLASS_NAME}_by_name(name string) *${CLASS_NAME} {
    invalid := &${CLASS_NAME}{Category_log: &bq.Category_log{Log: &bq.Log{}}, Cat: new_${CLASS_NAME}_category_root()}
    base := bq.Get_log_by_name(name)
    if base.Is_valid() && base.Get_categories_count() == len(${CLASS_NAME}_category_names) {
        for index, category := range ${CLASS_NAME}_category_names {
            if base.Get_category_name(index) != category {
                return invalid
            }
        }
        return &${CLASS_NAME}{Category_log: &bq.Category_log{Log: base}, Cat: new_${CLASS_NAME}_category_root()}
    }
    return invalid
}

func (l *${CLASS_NAME}) Verbose_c(category ${CLASS_NAME}_Category_ref, format string, args ...any) bool {
    return l.Category_log.Verbose_c(category.category_index(), format, args...)
}
func (l *${CLASS_NAME}) Debug_c(category ${CLASS_NAME}_Category_ref, format string, args ...any) bool {
    return l.Category_log.Debug_c(category.category_index(), format, args...)
}
func (l *${CLASS_NAME}) Info_c(category ${CLASS_NAME}_Category_ref, format string, args ...any) bool {
    return l.Category_log.Info_c(category.category_index(), format, args...)
}
func (l *${CLASS_NAME}) Warning_c(category ${CLASS_NAME}_Category_ref, format string, args ...any) bool {
    return l.Category_log.Warning_c(category.category_index(), format, args...)
}
func (l *${CLASS_NAME}) Error_c(category ${CLASS_NAME}_Category_ref, format string, args ...any) bool {
    return l.Category_log.Error_c(category.category_index(), format, args...)
}
func (l *${CLASS_NAME}) Fatal_c(category ${CLASS_NAME}_Category_ref, format string, args ...any) bool {
    return l.Category_log.Fatal_c(category.category_index(), format, args...)
}
)";
    }
}
