/* Copyright (C) 2026 Tencent. Licensed under the Apache License, Version 2.0. */
#include "template/category_log_template_go.h"

namespace bq {
    bq::string category_log_template_go::category_names(const category_node& node) const
    {
        bq::string code = "\t\"" + node.full_name() + "\",\n";
        for (const auto& child : node.get_all_children()) {
            code += category_names(*child);
        }
        return code;
    }

    bq::string category_log_template_go::category_constants(const category_node& node, uint64_t& index) const
    {
        // Length-prefixed segments avoid collisions between A.B and A_B.
        bq::string suffix = "Default";
        if (node.parent()) {
            suffix = "";
            for (const auto& segment : node.full_name().split(".")) {
                suffix += "_" + uint64_to_string(static_cast<uint64_t>(segment.size())) + "_" + segment;
            }
        }
        bq::string code = "\t" + class_name_ + "_Category_" + suffix + " " + class_name_ + "_Category = " + uint64_to_string(index++) + "\n";
        for (const auto& child : node.get_all_children()) {
            code += category_constants(*child, index);
        }
        return code;
    }

    bq::string category_log_template_go::format(const bq::string& template_string, const category_node& root_node) const
    {
        uint64_t index = 0;
        bq::string code = template_string.replace("${CLASS_NAME}", class_name_);
        code = code.replace("${CATEGORY_NAMES}", category_names(root_node));
        return code.replace("${CATEGORY_CONSTANTS}", category_constants(root_node, index));
    }

    bq::string category_log_template_go::get_template_content() const
    {
        return R"(// Code generated by BqLog_CategoryLogGenerator; DO NOT EDIT.
// Copyright (C) 2026 Tencent. Licensed under the Apache License, Version 2.0.
// Change the package declaration to the package of your application.
package bqlog_categories

import (
    bq "github.com/Tencent/BqLog/wrapper/go/src/bq"
)

type ${CLASS_NAME}_Category uint32

const (
${CATEGORY_CONSTANTS})

var ${CLASS_NAME}_category_names = []string{
${CATEGORY_NAMES}}

type ${CLASS_NAME} struct {
    *bq.Category_log
}

func Create_${CLASS_NAME}(name, config string) *${CLASS_NAME} {
    return &${CLASS_NAME}{bq.Create_category_log(name, config, ${CLASS_NAME}_category_names)}
}

func Get_${CLASS_NAME}_by_name(name string) *${CLASS_NAME} {
    base := bq.Get_log_by_name(name)
    if base.Is_valid() && base.Get_categories_count() == len(${CLASS_NAME}_category_names) {
        for index, category := range ${CLASS_NAME}_category_names {
            if base.Get_category_name(index) != category {
                return &${CLASS_NAME}{&bq.Category_log{Log: &bq.Log{}}}
            }
        }
        return &${CLASS_NAME}{&bq.Category_log{Log: base}}
    }
    return &${CLASS_NAME}{&bq.Category_log{Log: &bq.Log{}}}
}

func (l *${CLASS_NAME}) Verbose_c(category ${CLASS_NAME}_Category, format string, args ...any) bool {
    return l.Category_log.Verbose_c(uint32(category), format, args...)
}
func (l *${CLASS_NAME}) Debug_c(category ${CLASS_NAME}_Category, format string, args ...any) bool {
    return l.Category_log.Debug_c(uint32(category), format, args...)
}
func (l *${CLASS_NAME}) Info_c(category ${CLASS_NAME}_Category, format string, args ...any) bool {
    return l.Category_log.Info_c(uint32(category), format, args...)
}
func (l *${CLASS_NAME}) Warning_c(category ${CLASS_NAME}_Category, format string, args ...any) bool {
    return l.Category_log.Warning_c(uint32(category), format, args...)
}
func (l *${CLASS_NAME}) Error_c(category ${CLASS_NAME}_Category, format string, args ...any) bool {
    return l.Category_log.Error_c(uint32(category), format, args...)
}
func (l *${CLASS_NAME}) Fatal_c(category ${CLASS_NAME}_Category, format string, args ...any) bool {
    return l.Category_log.Fatal_c(uint32(category), format, args...)
}
)";
    }
}
