/* DO NOT EDIT THIS FILE - it is machine generated */
#ifndef _Included_com_tencent_bq_unittest_JNIEntry
#define _Included_com_tencent_bq_unittest_JNIEntry

#include <jni.h>
/* Header for class com_tencent_bq_unittest_JNIEntry */

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tencent_bq_unittest_JNIEntry
 * Method:    begin_test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tencent_bq_unittest_JNIEntry_begin_1test(JNIEnv*, jclass);

/*
 * Class:     com_tencent_bq_unittest_JNIEntry
 * Method:    get_current_test_result
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tencent_bq_unittest_JNIEntry_get_1current_1test_1result(JNIEnv*, jclass);

#ifdef __cplusplus
}
#endif

#endif
