package bq;
/*
 * Copyright (C) 2025 Tencent.
 * BQLOG is licensed under the Apache License, Version 2.0.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 */

import bq.def.*;
import bq.impl.log_invoker;

/*!
 * Generated Wrapper For test_category_log
 *
 * This is a category_log that supports attaching a category to each log entry.
 * Categories can be used to filter logs within the appender settings.
 *
 *    Usage: 
 *    bq.test_category_log my_category_log = bq.test_category_log::create_log(log_name, log_config);  //create a test_category_log object with config.
 *    my_category_log.info("content");  //this is for empty category
 *  my_category_log.info(my_category_log.cat.moduleA.classB, "content"); //this is a log entry for category ModuleA.ClassB, which was generated by your Category Config File
 */

public class test_category_log extends category_log{
    private test_category_log()
    {
        super();
    }
    
    private test_category_log(log child_inst)
    {
        super(child_inst);
    }
    
    /**
     * Create a test_category_log object
     * @param name 
     *             If the test_category_log name is an empty string, bqLog will automatically assign you a unique name. 
     *             If the test_category_log name already exists, it will return the previously existing test_category_log object and overwrite the previous configuration with the new config.
     * @param config
     *             test_category_log config string
     * @return
     *             A test_category_log object, if create failed, the is_valid() method of it will return false
     */
    public static test_category_log create_log(String name, String config)
    {
        if (config == null || config.length() == 0)
        {
            return new test_category_log();
        }
        long log_handle = log_invoker.__api_create_log(name, config, test_category_log.categories_count, test_category_log.category_names);
        log result = get_log_by_id(log_handle);
        return new test_category_log(result);
    }
    
    /**
     * Get a test_category_log object by it's name
     * @param log_name
     *             Name of the test_category_log you want to find
     * @return
     *             A test_category_log object, if the test_category_log object with specific name was not found, the is_valid() method of it will return false
     */
    public static test_category_log get_log_by_name(String log_name)
    {
        test_category_log result = new test_category_log(log.get_log_by_name(log_name));
        if(!result.is_valid())
        {
            return result;
        }
        //check categories
        if (result.get_categories_count() != test_category_log.categories_count)
        {
            return new test_category_log();
        }
        for (long i = 0; i < result.get_categories_count(); ++i)
        {
            if (!test_category_log.category_names[(int)i].equals(result.get_categories_name_array().get((int)i)))
            {
                return new test_category_log();
            }
        }
        return result;
    }
    

    //log methods for param count 0
    public boolean verbose(test_category_log_category_base category, String log_format_content)
    {
        return do_log(category, log_level.verbose, log_format_content);
    }
    public boolean debug(test_category_log_category_base category, String log_format_content)
    {
        return do_log(category, log_level.debug, log_format_content);
    }
    public boolean info(test_category_log_category_base category, String log_format_content)
    {
        return do_log(category, log_level.info, log_format_content);
    }
    public boolean warning(test_category_log_category_base category, String log_format_content)
    {
        return do_log(category, log_level.warning, log_format_content);
    }
    public boolean error(test_category_log_category_base category, String log_format_content)
    {
        return do_log(category, log_level.error, log_format_content);
    }
    public boolean fatal(test_category_log_category_base category, String log_format_content)
    {
        return do_log(category, log_level.fatal, log_format_content);
    }

    //log methods for param count 1
    public boolean verbose(test_category_log_category_base category, String log_format_content, Object p1)
    {
        return do_log(category, log_level.verbose, log_format_content, p1);
    }
    public boolean debug(test_category_log_category_base category, String log_format_content, Object p1)
    {
        return do_log(category, log_level.debug, log_format_content, p1);
    }
    public boolean info(test_category_log_category_base category, String log_format_content, Object p1)
    {
        return do_log(category, log_level.info, log_format_content, p1);
    }
    public boolean warning(test_category_log_category_base category, String log_format_content, Object p1)
    {
        return do_log(category, log_level.warning, log_format_content, p1);
    }
    public boolean error(test_category_log_category_base category, String log_format_content, Object p1)
    {
        return do_log(category, log_level.error, log_format_content, p1);
    }
    public boolean fatal(test_category_log_category_base category, String log_format_content, Object p1)
    {
        return do_log(category, log_level.fatal, log_format_content, p1);
    }

    //log methods for param count 2
    public boolean verbose(test_category_log_category_base category, String log_format_content, Object p1, Object p2)
    {
        return do_log(category, log_level.verbose, log_format_content, p1, p2);
    }
    public boolean debug(test_category_log_category_base category, String log_format_content, Object p1, Object p2)
    {
        return do_log(category, log_level.debug, log_format_content, p1, p2);
    }
    public boolean info(test_category_log_category_base category, String log_format_content, Object p1, Object p2)
    {
        return do_log(category, log_level.info, log_format_content, p1, p2);
    }
    public boolean warning(test_category_log_category_base category, String log_format_content, Object p1, Object p2)
    {
        return do_log(category, log_level.warning, log_format_content, p1, p2);
    }
    public boolean error(test_category_log_category_base category, String log_format_content, Object p1, Object p2)
    {
        return do_log(category, log_level.error, log_format_content, p1, p2);
    }
    public boolean fatal(test_category_log_category_base category, String log_format_content, Object p1, Object p2)
    {
        return do_log(category, log_level.fatal, log_format_content, p1, p2);
    }

    //log methods for param count 3
    public boolean verbose(test_category_log_category_base category, String log_format_content, Object p1, Object p2, Object p3)
    {
        return do_log(category, log_level.verbose, log_format_content, p1, p2, p3);
    }
    public boolean debug(test_category_log_category_base category, String log_format_content, Object p1, Object p2, Object p3)
    {
        return do_log(category, log_level.debug, log_format_content, p1, p2, p3);
    }
    public boolean info(test_category_log_category_base category, String log_format_content, Object p1, Object p2, Object p3)
    {
        return do_log(category, log_level.info, log_format_content, p1, p2, p3);
    }
    public boolean warning(test_category_log_category_base category, String log_format_content, Object p1, Object p2, Object p3)
    {
        return do_log(category, log_level.warning, log_format_content, p1, p2, p3);
    }
    public boolean error(test_category_log_category_base category, String log_format_content, Object p1, Object p2, Object p3)
    {
        return do_log(category, log_level.error, log_format_content, p1, p2, p3);
    }
    public boolean fatal(test_category_log_category_base category, String log_format_content, Object p1, Object p2, Object p3)
    {
        return do_log(category, log_level.fatal, log_format_content, p1, p2, p3);
    }

    //log methods for param count 4
    public boolean verbose(test_category_log_category_base category, String log_format_content, Object p1, Object p2, Object p3, Object p4)
    {
        return do_log(category, log_level.verbose, log_format_content, p1, p2, p3, p4);
    }
    public boolean debug(test_category_log_category_base category, String log_format_content, Object p1, Object p2, Object p3, Object p4)
    {
        return do_log(category, log_level.debug, log_format_content, p1, p2, p3, p4);
    }
    public boolean info(test_category_log_category_base category, String log_format_content, Object p1, Object p2, Object p3, Object p4)
    {
        return do_log(category, log_level.info, log_format_content, p1, p2, p3, p4);
    }
    public boolean warning(test_category_log_category_base category, String log_format_content, Object p1, Object p2, Object p3, Object p4)
    {
        return do_log(category, log_level.warning, log_format_content, p1, p2, p3, p4);
    }
    public boolean error(test_category_log_category_base category, String log_format_content, Object p1, Object p2, Object p3, Object p4)
    {
        return do_log(category, log_level.error, log_format_content, p1, p2, p3, p4);
    }
    public boolean fatal(test_category_log_category_base category, String log_format_content, Object p1, Object p2, Object p3, Object p4)
    {
        return do_log(category, log_level.fatal, log_format_content, p1, p2, p3, p4);
    }

    //log methods for param count 5
    public boolean verbose(test_category_log_category_base category, String log_format_content, Object p1, Object p2, Object p3, Object p4, Object p5)
    {
        return do_log(category, log_level.verbose, log_format_content, p1, p2, p3, p4, p5);
    }
    public boolean debug(test_category_log_category_base category, String log_format_content, Object p1, Object p2, Object p3, Object p4, Object p5)
    {
        return do_log(category, log_level.debug, log_format_content, p1, p2, p3, p4, p5);
    }
    public boolean info(test_category_log_category_base category, String log_format_content, Object p1, Object p2, Object p3, Object p4, Object p5)
    {
        return do_log(category, log_level.info, log_format_content, p1, p2, p3, p4, p5);
    }
    public boolean warning(test_category_log_category_base category, String log_format_content, Object p1, Object p2, Object p3, Object p4, Object p5)
    {
        return do_log(category, log_level.warning, log_format_content, p1, p2, p3, p4, p5);
    }
    public boolean error(test_category_log_category_base category, String log_format_content, Object p1, Object p2, Object p3, Object p4, Object p5)
    {
        return do_log(category, log_level.error, log_format_content, p1, p2, p3, p4, p5);
    }
    public boolean fatal(test_category_log_category_base category, String log_format_content, Object p1, Object p2, Object p3, Object p4, Object p5)
    {
        return do_log(category, log_level.fatal, log_format_content, p1, p2, p3, p4, p5);
    }

    //log methods for param count 6
    public boolean verbose(test_category_log_category_base category, String log_format_content, Object p1, Object p2, Object p3, Object p4, Object p5, Object p6)
    {
        return do_log(category, log_level.verbose, log_format_content, p1, p2, p3, p4, p5, p6);
    }
    public boolean debug(test_category_log_category_base category, String log_format_content, Object p1, Object p2, Object p3, Object p4, Object p5, Object p6)
    {
        return do_log(category, log_level.debug, log_format_content, p1, p2, p3, p4, p5, p6);
    }
    public boolean info(test_category_log_category_base category, String log_format_content, Object p1, Object p2, Object p3, Object p4, Object p5, Object p6)
    {
        return do_log(category, log_level.info, log_format_content, p1, p2, p3, p4, p5, p6);
    }
    public boolean warning(test_category_log_category_base category, String log_format_content, Object p1, Object p2, Object p3, Object p4, Object p5, Object p6)
    {
        return do_log(category, log_level.warning, log_format_content, p1, p2, p3, p4, p5, p6);
    }
    public boolean error(test_category_log_category_base category, String log_format_content, Object p1, Object p2, Object p3, Object p4, Object p5, Object p6)
    {
        return do_log(category, log_level.error, log_format_content, p1, p2, p3, p4, p5, p6);
    }
    public boolean fatal(test_category_log_category_base category, String log_format_content, Object p1, Object p2, Object p3, Object p4, Object p5, Object p6)
    {
        return do_log(category, log_level.fatal, log_format_content, p1, p2, p3, p4, p5, p6);
    }

    //log methods for param count 7
    public boolean verbose(test_category_log_category_base category, String log_format_content, Object p1, Object p2, Object p3, Object p4, Object p5, Object p6, Object p7)
    {
        return do_log(category, log_level.verbose, log_format_content, p1, p2, p3, p4, p5, p6, p7);
    }
    public boolean debug(test_category_log_category_base category, String log_format_content, Object p1, Object p2, Object p3, Object p4, Object p5, Object p6, Object p7)
    {
        return do_log(category, log_level.debug, log_format_content, p1, p2, p3, p4, p5, p6, p7);
    }
    public boolean info(test_category_log_category_base category, String log_format_content, Object p1, Object p2, Object p3, Object p4, Object p5, Object p6, Object p7)
    {
        return do_log(category, log_level.info, log_format_content, p1, p2, p3, p4, p5, p6, p7);
    }
    public boolean warning(test_category_log_category_base category, String log_format_content, Object p1, Object p2, Object p3, Object p4, Object p5, Object p6, Object p7)
    {
        return do_log(category, log_level.warning, log_format_content, p1, p2, p3, p4, p5, p6, p7);
    }
    public boolean error(test_category_log_category_base category, String log_format_content, Object p1, Object p2, Object p3, Object p4, Object p5, Object p6, Object p7)
    {
        return do_log(category, log_level.error, log_format_content, p1, p2, p3, p4, p5, p6, p7);
    }
    public boolean fatal(test_category_log_category_base category, String log_format_content, Object p1, Object p2, Object p3, Object p4, Object p5, Object p6, Object p7)
    {
        return do_log(category, log_level.fatal, log_format_content, p1, p2, p3, p4, p5, p6, p7);
    }

    //log methods for param count 8
    public boolean verbose(test_category_log_category_base category, String log_format_content, Object p1, Object p2, Object p3, Object p4, Object p5, Object p6, Object p7, Object p8)
    {
        return do_log(category, log_level.verbose, log_format_content, p1, p2, p3, p4, p5, p6, p7, p8);
    }
    public boolean debug(test_category_log_category_base category, String log_format_content, Object p1, Object p2, Object p3, Object p4, Object p5, Object p6, Object p7, Object p8)
    {
        return do_log(category, log_level.debug, log_format_content, p1, p2, p3, p4, p5, p6, p7, p8);
    }
    public boolean info(test_category_log_category_base category, String log_format_content, Object p1, Object p2, Object p3, Object p4, Object p5, Object p6, Object p7, Object p8)
    {
        return do_log(category, log_level.info, log_format_content, p1, p2, p3, p4, p5, p6, p7, p8);
    }
    public boolean warning(test_category_log_category_base category, String log_format_content, Object p1, Object p2, Object p3, Object p4, Object p5, Object p6, Object p7, Object p8)
    {
        return do_log(category, log_level.warning, log_format_content, p1, p2, p3, p4, p5, p6, p7, p8);
    }
    public boolean error(test_category_log_category_base category, String log_format_content, Object p1, Object p2, Object p3, Object p4, Object p5, Object p6, Object p7, Object p8)
    {
        return do_log(category, log_level.error, log_format_content, p1, p2, p3, p4, p5, p6, p7, p8);
    }
    public boolean fatal(test_category_log_category_base category, String log_format_content, Object p1, Object p2, Object p3, Object p4, Object p5, Object p6, Object p7, Object p8)
    {
        return do_log(category, log_level.fatal, log_format_content, p1, p2, p3, p4, p5, p6, p7, p8);
    }

    //log methods for param count 9
    public boolean verbose(test_category_log_category_base category, String log_format_content, Object p1, Object p2, Object p3, Object p4, Object p5, Object p6, Object p7, Object p8, Object p9)
    {
        return do_log(category, log_level.verbose, log_format_content, p1, p2, p3, p4, p5, p6, p7, p8, p9);
    }
    public boolean debug(test_category_log_category_base category, String log_format_content, Object p1, Object p2, Object p3, Object p4, Object p5, Object p6, Object p7, Object p8, Object p9)
    {
        return do_log(category, log_level.debug, log_format_content, p1, p2, p3, p4, p5, p6, p7, p8, p9);
    }
    public boolean info(test_category_log_category_base category, String log_format_content, Object p1, Object p2, Object p3, Object p4, Object p5, Object p6, Object p7, Object p8, Object p9)
    {
        return do_log(category, log_level.info, log_format_content, p1, p2, p3, p4, p5, p6, p7, p8, p9);
    }
    public boolean warning(test_category_log_category_base category, String log_format_content, Object p1, Object p2, Object p3, Object p4, Object p5, Object p6, Object p7, Object p8, Object p9)
    {
        return do_log(category, log_level.warning, log_format_content, p1, p2, p3, p4, p5, p6, p7, p8, p9);
    }
    public boolean error(test_category_log_category_base category, String log_format_content, Object p1, Object p2, Object p3, Object p4, Object p5, Object p6, Object p7, Object p8, Object p9)
    {
        return do_log(category, log_level.error, log_format_content, p1, p2, p3, p4, p5, p6, p7, p8, p9);
    }
    public boolean fatal(test_category_log_category_base category, String log_format_content, Object p1, Object p2, Object p3, Object p4, Object p5, Object p6, Object p7, Object p8, Object p9)
    {
        return do_log(category, log_level.fatal, log_format_content, p1, p2, p3, p4, p5, p6, p7, p8, p9);
    }

    //log methods for param count 10
    public boolean verbose(test_category_log_category_base category, String log_format_content, Object p1, Object p2, Object p3, Object p4, Object p5, Object p6, Object p7, Object p8, Object p9, Object p10)
    {
        return do_log(category, log_level.verbose, log_format_content, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10);
    }
    public boolean debug(test_category_log_category_base category, String log_format_content, Object p1, Object p2, Object p3, Object p4, Object p5, Object p6, Object p7, Object p8, Object p9, Object p10)
    {
        return do_log(category, log_level.debug, log_format_content, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10);
    }
    public boolean info(test_category_log_category_base category, String log_format_content, Object p1, Object p2, Object p3, Object p4, Object p5, Object p6, Object p7, Object p8, Object p9, Object p10)
    {
        return do_log(category, log_level.info, log_format_content, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10);
    }
    public boolean warning(test_category_log_category_base category, String log_format_content, Object p1, Object p2, Object p3, Object p4, Object p5, Object p6, Object p7, Object p8, Object p9, Object p10)
    {
        return do_log(category, log_level.warning, log_format_content, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10);
    }
    public boolean error(test_category_log_category_base category, String log_format_content, Object p1, Object p2, Object p3, Object p4, Object p5, Object p6, Object p7, Object p8, Object p9, Object p10)
    {
        return do_log(category, log_level.error, log_format_content, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10);
    }
    public boolean fatal(test_category_log_category_base category, String log_format_content, Object p1, Object p2, Object p3, Object p4, Object p5, Object p6, Object p7, Object p8, Object p9, Object p10)
    {
        return do_log(category, log_level.fatal, log_format_content, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10);
    }

    //log methods for param count 11
    public boolean verbose(test_category_log_category_base category, String log_format_content, Object p1, Object p2, Object p3, Object p4, Object p5, Object p6, Object p7, Object p8, Object p9, Object p10, Object p11)
    {
        return do_log(category, log_level.verbose, log_format_content, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11);
    }
    public boolean debug(test_category_log_category_base category, String log_format_content, Object p1, Object p2, Object p3, Object p4, Object p5, Object p6, Object p7, Object p8, Object p9, Object p10, Object p11)
    {
        return do_log(category, log_level.debug, log_format_content, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11);
    }
    public boolean info(test_category_log_category_base category, String log_format_content, Object p1, Object p2, Object p3, Object p4, Object p5, Object p6, Object p7, Object p8, Object p9, Object p10, Object p11)
    {
        return do_log(category, log_level.info, log_format_content, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11);
    }
    public boolean warning(test_category_log_category_base category, String log_format_content, Object p1, Object p2, Object p3, Object p4, Object p5, Object p6, Object p7, Object p8, Object p9, Object p10, Object p11)
    {
        return do_log(category, log_level.warning, log_format_content, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11);
    }
    public boolean error(test_category_log_category_base category, String log_format_content, Object p1, Object p2, Object p3, Object p4, Object p5, Object p6, Object p7, Object p8, Object p9, Object p10, Object p11)
    {
        return do_log(category, log_level.error, log_format_content, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11);
    }
    public boolean fatal(test_category_log_category_base category, String log_format_content, Object p1, Object p2, Object p3, Object p4, Object p5, Object p6, Object p7, Object p8, Object p9, Object p10, Object p11)
    {
        return do_log(category, log_level.fatal, log_format_content, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11);
    }

    //log methods for param count 12
    public boolean verbose(test_category_log_category_base category, String log_format_content, Object p1, Object p2, Object p3, Object p4, Object p5, Object p6, Object p7, Object p8, Object p9, Object p10, Object p11, Object p12)
    {
        return do_log(category, log_level.verbose, log_format_content, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12);
    }
    public boolean debug(test_category_log_category_base category, String log_format_content, Object p1, Object p2, Object p3, Object p4, Object p5, Object p6, Object p7, Object p8, Object p9, Object p10, Object p11, Object p12)
    {
        return do_log(category, log_level.debug, log_format_content, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12);
    }
    public boolean info(test_category_log_category_base category, String log_format_content, Object p1, Object p2, Object p3, Object p4, Object p5, Object p6, Object p7, Object p8, Object p9, Object p10, Object p11, Object p12)
    {
        return do_log(category, log_level.info, log_format_content, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12);
    }
    public boolean warning(test_category_log_category_base category, String log_format_content, Object p1, Object p2, Object p3, Object p4, Object p5, Object p6, Object p7, Object p8, Object p9, Object p10, Object p11, Object p12)
    {
        return do_log(category, log_level.warning, log_format_content, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12);
    }
    public boolean error(test_category_log_category_base category, String log_format_content, Object p1, Object p2, Object p3, Object p4, Object p5, Object p6, Object p7, Object p8, Object p9, Object p10, Object p11, Object p12)
    {
        return do_log(category, log_level.error, log_format_content, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12);
    }
    public boolean fatal(test_category_log_category_base category, String log_format_content, Object p1, Object p2, Object p3, Object p4, Object p5, Object p6, Object p7, Object p8, Object p9, Object p10, Object p11, Object p12)
    {
        return do_log(category, log_level.fatal, log_format_content, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12);
    }

    ///Core log functions with category param, there are 6 log levels:
    ///verbose, debug, info, warning, error, fatal
    public boolean verbose(test_category_log_category_base category, String log_format_content, Object... args)
    {
        return do_log(category, log_level.verbose, log_format_content, args);
    }
    public boolean debug(test_category_log_category_base category, String log_format_content, Object... args)
    {
        return do_log(category, log_level.debug, log_format_content, args);
    }
    public boolean info(test_category_log_category_base category, String log_format_content, Object... args)
    {
        return do_log(category, log_level.info, log_format_content, args);
    }
    public boolean warning(test_category_log_category_base category, String log_format_content, Object... args)
    {
        return do_log(category, log_level.warning, log_format_content, args);
    }
    public boolean error(test_category_log_category_base category, String log_format_content, Object... args)
    {
        return do_log(category, log_level.error, log_format_content, args);
    }
    public boolean fatal(test_category_log_category_base category, String log_format_content, Object... args)
    {
        return do_log(category, log_level.fatal, log_format_content, args);
    }
    
    
    
    
    /****************************************************************************************************************/
    /**                                 Code Generated By Categories                                              ***/
    /****************************************************************************************************************/
    private static final String[] category_names = {
                                                       ""
                                                       , "ModuleA"
                                                       , "ModuleA.SystemA"
                                                       , "ModuleA.SystemA.ClassA"
                                                       , "ModuleB"
                                                   };
    private static final long categories_count = (long)category_names.length;
    private static class test_category_log_category_base extends log_category_base
    {
    }
    public static class test_category_log_category_root
    {
        public static class test_category_log_ModuleA extends test_category_log_category_base
        {
            public test_category_log_ModuleA(){index = 1L;}
            public static class test_category_log_SystemA extends test_category_log_category_base
            {
                public test_category_log_SystemA(){index = 2L;}
                public static class test_category_log_ClassA extends test_category_log_category_base
                {
                    public test_category_log_ClassA(){index = 3L;}
                }
                public test_category_log_ClassA ClassA = new test_category_log_ClassA();     //ModuleA.SystemA.ClassA
            }
            public test_category_log_SystemA SystemA = new test_category_log_SystemA();     //ModuleA.SystemA
        }
        public test_category_log_ModuleA ModuleA = new test_category_log_ModuleA();     //ModuleA
        public static class test_category_log_ModuleB extends test_category_log_category_base
        {
            public test_category_log_ModuleB(){index = 4L;}
        }
        public test_category_log_ModuleB ModuleB = new test_category_log_ModuleB();     //ModuleB
    }
    
    public final test_category_log_category_root cat = new test_category_log_category_root();
}
