// Code generated by BqLog_CategoryLogGenerator; DO NOT EDIT.
// Copyright (C) 2026 Tencent. Licensed under the Apache License, Version 2.0.
// Change the package declaration to the package of your application.
//
// Usage:
//
//	log := Create_demo_category_log(log_name, log_config)
//	log.Info("content")                            // empty category
//	log.Info_c(log.Cat.ModuleA.SystemA, "content") // a log entry for category ModuleA.SystemA, generated from your Category Config File
package main

import (
	bq "github.com/Tencent/BqLog/wrapper/go/src/bq"
)

type demo_category_log_Category uint32

func (c demo_category_log_Category) category_index() uint32 { return uint32(c) }

type demo_category_log_Category_ref interface {
	category_index() uint32
}

type demo_category_log_category_root struct {
	Node_2 demo_category_log_node_6_node_2 // node_2
	Node_3 demo_category_log_node_6_node_3 // node_3
	Node_4 demo_category_log_node_6_node_4 // node_4
}

type demo_category_log_node_6_node_2 struct {
	demo_category_log_Category
	Node_5 demo_category_log_Category // node_2.node_5
}

type demo_category_log_node_6_node_3 struct {
	demo_category_log_Category
	Node_6  demo_category_log_Category // node_3.node_6 - comment Test
	Node_10 demo_category_log_Category // node_3.node_10
}

type demo_category_log_node_6_node_4 struct {
	demo_category_log_Category
	Node_7 demo_category_log_node_6_node_4_6_node_7 // node_4.node_7
}

type demo_category_log_node_6_node_4_6_node_7 struct {
	demo_category_log_Category
	Node_8 demo_category_log_Category // node_4.node_7.node_8
	Node_9 demo_category_log_Category // node_4.node_7.node_9
}

func new_demo_category_log_category_root() demo_category_log_category_root {
	var root demo_category_log_category_root
	root.Node_2.demo_category_log_Category = 1
	root.Node_2.Node_5 = 2
	root.Node_3.demo_category_log_Category = 3
	root.Node_3.Node_6 = 4
	root.Node_3.Node_10 = 5
	root.Node_4.demo_category_log_Category = 6
	root.Node_4.Node_7.demo_category_log_Category = 7
	root.Node_4.Node_7.Node_8 = 8
	root.Node_4.Node_7.Node_9 = 9
	return root
}

var demo_category_log_category_names = []string{
	"",
	"node_2",
	"node_2.node_5",
	"node_3",
	"node_3.node_6",
	"node_3.node_10",
	"node_4",
	"node_4.node_7",
	"node_4.node_7.node_8",
	"node_4.node_7.node_9",
}

type demo_category_log struct {
	*bq.Category_log
	Cat demo_category_log_category_root
}

func Create_demo_category_log(name, config string) *demo_category_log {
	return &demo_category_log{Category_log: bq.Create_category_log(name, config, demo_category_log_category_names), Cat: new_demo_category_log_category_root()}
}

func Get_demo_category_log_by_name(name string) *demo_category_log {
	invalid := &demo_category_log{Category_log: &bq.Category_log{Log: &bq.Log{}}, Cat: new_demo_category_log_category_root()}
	base := bq.Get_log_by_name(name)
	if base.Is_valid() && base.Get_categories_count() == len(demo_category_log_category_names) {
		for index, category := range demo_category_log_category_names {
			if base.Get_category_name(index) != category {
				return invalid
			}
		}
		return &demo_category_log{Category_log: &bq.Category_log{Log: base}, Cat: new_demo_category_log_category_root()}
	}
	return invalid
}

func (l *demo_category_log) Verbose_c(category demo_category_log_Category_ref, format string, args ...any) bool {
	return l.Category_log.Verbose_c(category.category_index(), format, args...)
}
func (l *demo_category_log) Debug_c(category demo_category_log_Category_ref, format string, args ...any) bool {
	return l.Category_log.Debug_c(category.category_index(), format, args...)
}
func (l *demo_category_log) Info_c(category demo_category_log_Category_ref, format string, args ...any) bool {
	return l.Category_log.Info_c(category.category_index(), format, args...)
}
func (l *demo_category_log) Warning_c(category demo_category_log_Category_ref, format string, args ...any) bool {
	return l.Category_log.Warning_c(category.category_index(), format, args...)
}
func (l *demo_category_log) Error_c(category demo_category_log_Category_ref, format string, args ...any) bool {
	return l.Category_log.Error_c(category.category_index(), format, args...)
}
func (l *demo_category_log) Fatal_c(category demo_category_log_Category_ref, format string, args ...any) bool {
	return l.Category_log.Fatal_c(category.category_index(), format, args...)
}
