// Code generated by BqLog_CategoryLogGenerator; DO NOT EDIT.
// Copyright (C) 2026 Tencent. Licensed under the Apache License, Version 2.0.
// Change the package declaration to the package of your application.
//
// Usage:
//
//	log := Create_Generated_category(log_name, log_config)
//	log.Info("content")                            // empty category
//	log.Info_c(log.Cat.ModuleA.SystemA, "content") // a log entry for category ModuleA.SystemA, generated from your Category Config File
package bqlog_categories

import (
	bq "github.com/Tencent/BqLog/wrapper/go/src/bq"
)

type Generated_category_Category uint32

func (c Generated_category_Category) category_index() uint32 { return uint32(c) }

type Generated_category_Category_ref interface {
	category_index() uint32
}

type Generated_category_category_root struct {
	ModuleA Generated_category_node_7_ModuleA // ModuleA
	ModuleB Generated_category_Category       // ModuleB
	A_B     Generated_category_Category       // A_B
	A       Generated_category_node_1_A       // A
}

type Generated_category_node_7_ModuleA struct {
	Generated_category_Category
	SystemA Generated_category_node_7_ModuleA_7_SystemA // ModuleA.SystemA
}

type Generated_category_node_7_ModuleA_7_SystemA struct {
	Generated_category_Category
	ClassA Generated_category_Category // ModuleA.SystemA.ClassA
}

type Generated_category_node_1_A struct {
	Generated_category_Category
	B Generated_category_Category // A.B
}

func new_Generated_category_category_root() Generated_category_category_root {
	var root Generated_category_category_root
	root.ModuleA.Generated_category_Category = 1
	root.ModuleA.SystemA.Generated_category_Category = 2
	root.ModuleA.SystemA.ClassA = 3
	root.ModuleB = 4
	root.A_B = 5
	root.A.Generated_category_Category = 6
	root.A.B = 7
	return root
}

var Generated_category_category_names = []string{
	"",
	"ModuleA",
	"ModuleA.SystemA",
	"ModuleA.SystemA.ClassA",
	"ModuleB",
	"A_B",
	"A",
	"A.B",
}

type Generated_category struct {
	*bq.Category_log
	Cat Generated_category_category_root
}

func Create_Generated_category(name, config string) *Generated_category {
	return &Generated_category{Category_log: bq.Create_category_log(name, config, Generated_category_category_names), Cat: new_Generated_category_category_root()}
}

func Get_Generated_category_by_name(name string) *Generated_category {
	invalid := &Generated_category{Category_log: &bq.Category_log{Log: &bq.Log{}}, Cat: new_Generated_category_category_root()}
	base := bq.Get_log_by_name(name)
	if base.Is_valid() && base.Get_categories_count() == len(Generated_category_category_names) {
		for index, category := range Generated_category_category_names {
			if base.Get_category_name(index) != category {
				return invalid
			}
		}
		return &Generated_category{Category_log: &bq.Category_log{Log: base}, Cat: new_Generated_category_category_root()}
	}
	return invalid
}

func (l *Generated_category) Verbose_c(category Generated_category_Category_ref, format string, args ...any) bool {
	return l.Category_log.Verbose_c(category.category_index(), format, args...)
}
func (l *Generated_category) Debug_c(category Generated_category_Category_ref, format string, args ...any) bool {
	return l.Category_log.Debug_c(category.category_index(), format, args...)
}
func (l *Generated_category) Info_c(category Generated_category_Category_ref, format string, args ...any) bool {
	return l.Category_log.Info_c(category.category_index(), format, args...)
}
func (l *Generated_category) Warning_c(category Generated_category_Category_ref, format string, args ...any) bool {
	return l.Category_log.Warning_c(category.category_index(), format, args...)
}
func (l *Generated_category) Error_c(category Generated_category_Category_ref, format string, args ...any) bool {
	return l.Category_log.Error_c(category.category_index(), format, args...)
}
func (l *Generated_category) Fatal_c(category Generated_category_Category_ref, format string, args ...any) bool {
	return l.Category_log.Fatal_c(category.category_index(), format, args...)
}
