// Code generated by BqLog_CategoryLogGenerator; DO NOT EDIT.
// Copyright (C) 2026 Tencent. Licensed under the Apache License, Version 2.0.
// Change the package declaration to the package of your application.
//
// Usage:
//
//	log := Create_test_category_log(log_name, log_config)
//	log.Info("content")                            // empty category
//	log.Info_c(log.Cat.ModuleA.SystemA, "content") // a log entry for category ModuleA.SystemA, generated from your Category Config File
package main

import (
	bq "github.com/Tencent/BqLog/wrapper/go/src/bq"
)

type test_category_log_Category uint32

func (c test_category_log_Category) category_index() uint32 { return uint32(c) }

type test_category_log_Category_ref interface {
	category_index() uint32
}

type test_category_log_category_root struct {
	ModuleA test_category_log_node_7_ModuleA // ModuleA
	ModuleB test_category_log_Category       // ModuleB
}

type test_category_log_node_7_ModuleA struct {
	test_category_log_Category
	SystemA test_category_log_node_7_ModuleA_7_SystemA // ModuleA.SystemA
}

type test_category_log_node_7_ModuleA_7_SystemA struct {
	test_category_log_Category
	ClassA test_category_log_Category // ModuleA.SystemA.ClassA
}

func new_test_category_log_category_root() test_category_log_category_root {
	var root test_category_log_category_root
	root.ModuleA.test_category_log_Category = 1
	root.ModuleA.SystemA.test_category_log_Category = 2
	root.ModuleA.SystemA.ClassA = 3
	root.ModuleB = 4
	return root
}

var test_category_log_category_names = []string{
	"",
	"ModuleA",
	"ModuleA.SystemA",
	"ModuleA.SystemA.ClassA",
	"ModuleB",
}

type test_category_log struct {
	*bq.Category_log
	Cat test_category_log_category_root
}

func Create_test_category_log(name, config string) *test_category_log {
	return &test_category_log{Category_log: bq.Create_category_log(name, config, test_category_log_category_names), Cat: new_test_category_log_category_root()}
}

func Get_test_category_log_by_name(name string) *test_category_log {
	invalid := &test_category_log{Category_log: &bq.Category_log{Log: &bq.Log{}}, Cat: new_test_category_log_category_root()}
	base := bq.Get_log_by_name(name)
	if base.Is_valid() && base.Get_categories_count() == len(test_category_log_category_names) {
		for index, category := range test_category_log_category_names {
			if base.Get_category_name(index) != category {
				return invalid
			}
		}
		return &test_category_log{Category_log: &bq.Category_log{Log: base}, Cat: new_test_category_log_category_root()}
	}
	return invalid
}

func (l *test_category_log) Verbose_c(category test_category_log_Category_ref, format string, args ...any) bool {
	return l.Category_log.Verbose_c(category.category_index(), format, args...)
}
func (l *test_category_log) Debug_c(category test_category_log_Category_ref, format string, args ...any) bool {
	return l.Category_log.Debug_c(category.category_index(), format, args...)
}
func (l *test_category_log) Info_c(category test_category_log_Category_ref, format string, args ...any) bool {
	return l.Category_log.Info_c(category.category_index(), format, args...)
}
func (l *test_category_log) Warning_c(category test_category_log_Category_ref, format string, args ...any) bool {
	return l.Category_log.Warning_c(category.category_index(), format, args...)
}
func (l *test_category_log) Error_c(category test_category_log_Category_ref, format string, args ...any) bool {
	return l.Category_log.Error_c(category.category_index(), format, args...)
}
func (l *test_category_log) Fatal_c(category test_category_log_Category_ref, format string, args ...any) bool {
	return l.Category_log.Fatal_c(category.category_index(), format, args...)
}
