name: Build
on:  
  workflow_dispatch:  # manually trigger
  workflow_call:

permissions:
  contents: write

jobs:
  #Windows
  build_windows_static_lib_MSVC:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build for Windows
        run: |
          cd build\lib\win64  
          .\BuildAll_AndPack_MSVC.bat
        env:
          VS_PATH: "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\Common7\\IDE"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: win64_libs_msvc
          path: dist\

  build_windows_dynamic_lib_MSVC:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build for Windows
        run: |
          cd build\lib\win64  
          .\BuildAll_AndPack_Clang.bat 
        env:
          VS_PATH: "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\Common7\\IDE"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: win64_libs_clang
          path: dist\

  build_windows_tools:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build Tools
        run: |
          cd build\tools\win64 
          .\BuildAll_And_Pack_Tools.bat
        env:
          VS_PATH: "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\Common7\\IDE"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: win64_tools
          path: bin\tools\win64

  #Android
  build_windows_android:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          
      - name: Set up Android SDK (with NDK)
        id: setup-android
        uses: android-actions/setup-android@v3
        
      - name: Set up NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r28c
          local-cache: false

      - name: Build for Windows Android
        run: |
          cd build\lib\android
          .\Win_BuildAll_AndPack.bat 
        env:
          ANDROID_NDK_ROOT: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android_artifact
          path: dist\

  build_mac_android:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          
      - name: Set up Android SDK (with NDK)
        id: setup-android
        uses: android-actions/setup-android@v3
        
      - name: Set up NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r28c
          local-cache: false

      - name: Build for Mac Android
        run: |
          cd build/lib/android
          chmod +x *.sh
          ./Mac_Build_Dynamic_Lib.sh 
        env:
          ANDROID_NDK_ROOT: ${{ steps.setup-ndk.outputs.ndk-path }}

  build_linux_android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          
      - name: Set up Android SDK (with NDK)
        id: setup-android
        uses: android-actions/setup-android@v3
        
      - name: Set up NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r28c
          local-cache: false

      - name: Build for Windows Android
        run: |
          cd build\lib\android
          .\Linux_BuildAll_AndPack.bat 
        env:
          ANDROID_NDK_ROOT: ${{ steps.setup-ndk.outputs.ndk-path }}
